package org.training.issuetracker.dao.xml.parsers.enums;

public enum XMLTag {
	ISSUETRACKER, ROLES, ROLE, ISSUE_STATUSES, STATUS, ISSUE_RESOLUTIONS, RESOLUTION, 
	ISSUE_PRIORITIES, PRIORITY, ISSUE_TYPES, TYPE, USERS, USER,
	FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, PASSWORD, MANAGERS, MANAGER,
	PROJECTS, PROJECT, BUILDS, BUILD, NAME, DESCRIPTION, ISSUES, ISSUE,
	CREATE_DATE, CREATED_BY, MODIFY_DATE, MODIFY_BY, SUMMARY, BUILD_FOUND,
	ASSIGNEE;
}
